const { createCanvas, loadImage } = require('canvas');


function explode(text, max) {
	if (text == null) return '';
	if (text.length <= max) return text;
	const nextNewLine = /\n/.exec(text);
	const lineLength = nextNewLine ? nextNewLine.index : text.length;
	if (lineLength <= max) {
		const line = text.substr(0, lineLength);
		const rest = text.substr(lineLength + 1);
		return line + '\n' + explode(rest, max);
	}
	else {
		let line = text.substr(0, max);
		let rest = text.substr(max);
		const res = (/([\s])[^\s]*$/.exec(line));
		if (res) {
			line = text.substr(0, res.index);
			rest = text.substr(res.index + 1);
		}
		else {
			line = line + '-';
		}
		return line + '\n' + explode(rest, max);
	}
}
/**
 * @param {import('discord.js').ChatInputCommandInteraction} interaction
 * @param {import('discord.js').Message} message
 */
module.exports = async (interaction, message) => {
	const canvas = createCanvas(1920, 1080);
	const ctx = canvas.getContext('2d');
	ctx.fillStyle = 'rgba(49, 51, 56, 1)';
	ctx.fillRect(0, 0, canvas.width, canvas.height);

	// ctx.fillStyle = 'black';
	ctx.shadowColor = 'black';
	ctx.shadowBlur = 5;
	ctx.shadowOffsetX = 0;
	ctx.shadowOffsetY = 5;
	ctx.fillRect(0, 250, canvas.width, 1);

	await loadImage(interaction.guild.iconURL({ extension: 'png' })).then(image => {
		ctx.save();
		ctx.beginPath();
		ctx.arc(125, 125, 100, 0, Math.PI * 2, true);
		ctx.closePath();
		ctx.clip();
		ctx.drawImage(image, 25, 25, 200, 200);
		ctx.restore();
	});

	ctx.fillStyle = 'white';
	ctx.font = '80px sans-serif';
	ctx.fillText(interaction.guild.name, 250, 125);
	ctx.font = '50px sans-serif';
	ctx.fillText(`In channel: #${interaction.channel.name}`, 260, 200);

	await loadImage(message.member.displayAvatarURL({ extension: 'png' })).then(image => {
		ctx.save();
		ctx.beginPath();
		ctx.arc(200, 450, 95, 0, Math.PI * 2, true);
		ctx.closePath();
		ctx.clip();
		ctx.drawImage(image, 105, 355, 190, 190);
		ctx.restore();
	});

	ctx.font = '60px sans-serif';
	ctx.fillText(message.member.displayName, 330, 440);
	ctx.font = '40px sans-serif';
	ctx.fillText(explode(message.content, 85), 340, 520, 1500);
	ctx.fillStyle = 'rgba(39, 41, 45, 1)';
	ctx.fillRect(0, 1020, canvas.width, 60);
	ctx.font = '30px sans-serif';
	ctx.textAlign = 'center';
	ctx.fillStyle = 'white';
	ctx.textBaseline = 'middle';
	ctx.fillText('● This photo was generated by our automated system. (it considered a valid proof by our staff team)', canvas.width / 2, 1050);
	return canvas.toBuffer();
};